[chartable]
'ン' = ['n', 'm']
'ヲ' = 'wo'
'ワ' = 'wa'
'ロ' = 'ro'
'レ' = 're'
'ル' = 'ru'
'リ' = 'ri'
'ラ' = 'ra'
'ヨ' = 'yo'
'ユ' = 'yu'
'ヤ' = 'ya'
'モ' = 'mo'
'メ' = 'me'
'ム' = 'mu'
'ミ' = 'mi'
'マ' = 'ma'
'ホ' = 'ho'
'ヘ' = 'he'
'フ' = 'fu'
'ヒ' = 'hi'
'ハ' = 'ha'
'ノ' = 'no'
'ネ' = 'ne'
'ヌ' = 'nu'
'ニ' = 'ni'
'ナ' = 'na'
'ト' = 'to'
'テ' = 'te'
'ツ' = 'tsu'
'チ' = 'chi'
'タ' = 'ta'
'ソ' = 'so'
'セ' = 'se'
'ス' = 'su'
'シ' = 'shi'
'サ' = 'sa'
'コ' = 'ko'
'ケ' = 'ke'
'ク' = 'ku'
'キ' = 'ki'
'カ' = 'ka'
'オ' = 'o'
'エ' = 'e'
'ウ' = 'u'
'イ' = 'i'
'ア' = 'a'